CREATE TABLE Users (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  Name TEXT NOT NULL,
  DisplayName TEXT,
  RegisterDate TEXT NOT NULL,
  Password TEXT NOT NULL,
  Salt TEXT NOT NULL
);

CREATE TABLE Posts (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  UserId INTEGER NOT NULL,
  SubmitTime TEXT NOT NULL,
  Text TEXT NOT NULL,
  FOREIGN KEY(UserId) REFERENCES Users(Id)
);

CREATE TABLE Replies (
  Id INTEGER PRIMARY KEY AUTOINCREMENT,
  PostId INTEGER NOT NULL,
  UserId INTEGER NOT NULL,
  SubmitTime TEXT NOT NULL,
  Text TEXT NOT NULL,
  FOREIGN KEY(PostId) REFERENCES Posts(Id),
  FOREIGN KEY(UserId) REFERENCES Users(Id)
);